spring.application.name=eschool
server.port=8082

# =========================================
# POSTGRESQL - NEON DB
# =========================================
spring.datasource.url=jdbc:postgresql://ep-fragrant-mouse-axl8jyia-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require&scramMinIterations=4096
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Xb23UekoIDQj
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================
# HIKARI CONNECTION POOL
# =========================================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# =========================================
# JPA / HIBERNATE
# =========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================================
# LOGGING SQL
# =========================================
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter.json=TRACE
logging.level.com.fasterxml.jackson=TRACE
server.error.include-message=always
server.error.include-stacktrace=always

# =========================================
# JACKSON JSON
# =========================================
spring.jackson.serialization.indent-output=true

# =========================================
# FILE UPLOAD
# =========================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

#logging.level.root=INFO
#logging.level.org.springframework=DEBUG
#app.front-url=https://uchurche.vercel.app
app.front-url=http://10.183.246.177:4200
# Supabase Storage
supabase.url=https://cqxcdbwrdyjperpqkngd.supabase.co
supabase.storage-url=https://cqxcdbwrdyjperpqkngd.supabase.co/storage/v1
supabase.bucket=Elearning
supabase.service-role-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxeGNkYndyZHlqcGVycHFrbmdkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MzQwNjAxNSwiZXhwIjoyMDg4OTgyMDE1fQ.2UCWipodoeiSU6VS8fpNYTpBV8mWj9szeGkVMAo7tSo



# MAIL (SMTP GMAIL)
# =================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kingproduct45@gmail.com
spring.mail.password=xovb nmbg qmmx wgwl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8

# =================================================
# TASK SCHEDULING
# =================================================
spring.task.scheduling.pool.size=5
